FROM docker.io/tfeltin/python3-ort-opencv:cuda

ENV PROVIDERS="['CUDAExecutionProvider', 'CPUExecutionProvider']"

WORKDIR /usr/src/app

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY . .
